# Generated by Django 2.0.5 on 2019-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregisters_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
