# Generated by Django 2.0.5 on 2019-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userwateranalysis_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useridorbillno', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
                ('now', models.CharField(max_length=20)),
                ('nol', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('wpd', models.CharField(max_length=20)),
                ('receipt', models.CharField(max_length=20)),
                ('bookdate', models.DateField(max_length=50)),
                ('deliverydate', models.DateField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='userregisters_model',
            old_name='username',
            new_name='name',
        ),
    ]
