# Generated by Django 2.0.5 on 2019-02-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0002_auto_20190201_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisters_model',
            old_name='Password',
            new_name='password',
        ),
    ]
