# Generated by Django 2.0.5 on 2019-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0003_auto_20190201_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfeedback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('branches', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=300)),
                ('emailid', models.CharField(max_length=300)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='userwateranalysis_model',
            name='uregid',
            field=models.ForeignKey(default='', on_delete='CASCADE', to='Users_Controller.Userregisters_Model'),
            preserve_default=False,
        ),
    ]
