# Generated by Django 2.0.5 on 2019-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0004_auto_20190201_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback_model',
            name='emailid',
            field=models.EmailField(max_length=300),
        ),
    ]
