# Generated by Django 2.0.5 on 2019-02-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0006_userfeedback_model_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback_model',
            name='topics',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback_model',
            name='uregsid',
            field=models.ForeignKey(default='', on_delete='cascade', to='Users_Controller.Userregisters_Model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userwateranalysis_model',
            name='uregid',
            field=models.ForeignKey(on_delete='cascade', to='Users_Controller.Userregisters_Model'),
        ),
    ]
