# Generated by Django 2.0.5 on 2019-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0007_auto_20190202_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback_model',
            name='topics',
            field=models.CharField(max_length=200),
        ),
    ]
