# Generated by Django 2.0.5 on 2019-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Controller', '0008_auto_20190202_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback_model',
            name='emailid',
        ),
        migrations.AddField(
            model_name='userfeedback_model',
            name='sentiment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
